version: 2

project_name: mc-router
release:
  github:
    owner: wroud
    name: mc-router
before:
  hooks:
    - go mod download
builds:
  - id: mc-router
    main: ./cmd/mc-router
    binary: mc-router
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE*
      - README*
dockers:
  - image_templates:
      - "wroud/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "wroud/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile.release
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/amd64
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "wroud/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "wroud/{{ .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile.release
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm64
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "wroud/{{ .ProjectName }}:{{ .Version }}-arm32v6"
      - "wroud/{{ .ProjectName }}:latest-arm32v6"
    dockerfile: Dockerfile.release
    goarch: arm
    goarm: "6"
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm/v6
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "ghcr.io/wroud/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/wroud/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile.release
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/amd64
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "ghcr.io/wroud/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/wroud/{{ .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile.release
    goarch: arm64
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm64
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "ghcr.io/wroud/{{ .ProjectName }}:{{ .Version }}-arm32v6"
      - "ghcr.io/wroud/{{ .ProjectName }}:latest-arm32v6"
    dockerfile: Dockerfile.release
    goarch: arm
    goarm: "6"
    use: buildx
    build_flag_templates:
      - --platform
      - linux/arm/v6
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
  - name_template: "wroud/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "wroud/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "wroud/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "wroud/{{ .ProjectName }}:{{ .Version }}-arm32v6"
  - name_template: "wroud/{{ .ProjectName }}:latest"
    image_templates:
      - "wroud/{{ .ProjectName }}:latest-amd64"
      - "wroud/{{ .ProjectName }}:latest-arm64"
      - "wroud/{{ .ProjectName }}:latest-arm32v6"
  - name_template: "ghcr.io/wroud/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/wroud/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/wroud/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/wroud/{{ .ProjectName }}:{{ .Version }}-arm32v6"
  - name_template: "ghcr.io/wroud/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/wroud/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/wroud/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/wroud/{{ .ProjectName }}:latest-arm32v6"
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^misc:'
      - '^test:'
