name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: wroud/github-workflows/.github/workflows/go-test.yml@main
    with:
      go-version-file: 'go.mod'
